name: Github Tag

on:
  push:
    branches:
      - production

jobs:
  package:
    name: Build and publish the package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Register the current Git user name
        run: git config user.name ${{ secrets.WORKFLOW_GITHUB_USERNAME }}

      - name: Register the current Git user email
        run: git config user.email ${{ secrets.WORKFLOW_GITHUB_EMAIL }}

      - name: Creating tag
        run: git tag -a $(cat package.json | grep -i version | sed -e "s/ //g" | cut -c 12- | sed -e "s/\",//g") -m "$(cat package.json | grep -i version | sed -e "s/ //g" | cut -c 12- | sed -e "s/\",//g")"

      - name: Publish tag
        run: 'git push origin $(cat package.json | grep -i version | sed -e "s/ //g" | cut -c 12- | sed -e "s/\",//g") || true'
